# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  BASE_BINDIR: build
  TEST_SRCDIR: test/release
  TEST_ENVDIR: utils/ewasm-testbench
  LIT_PATH: /usr/lib/llvm-8/build/utils/lit/lit.py
  EVM_BINDIR: /evm_llvm_build
  EVM_LIT_PATH: ${EVM_BINDIR}/bin/llvm-lit

stages:
  - build
  - compile
  - test
  - deploy

# Templates
.before_build: &before_build
  - rm -rf ${BASE_BINDIR}
  - mkdir ${BASE_BINDIR}
  - cd ${BASE_BINDIR}

.cache_paths: &cache_paths
  paths:
    - ${BASE_BINDIR}

.build_job_template: &build_job
  stage: build
  image: secondstate/soll:${KEY}
  before_script:
    - *before_build
  script:
    - cmake .. ${CMAKE_OPTIONS}
    - make -j2
  cache:
    <<: *cache_paths
    key: ${KEY}
    policy: push

# General Build Jobs
ubuntu-gcc:
  <<: *build_job
  tags: ["gcc"]
  variables:
    CMAKE_OPTIONS: "-DCMAKE_BUILD_TYPE=Debug -DSOLL_INCLUDE_TESTS=true -DLLVM_EXTERNAL_LIT=${LIT_PATH}"
    KEY: "ubuntu-gcc"

ubuntu-clang:
  <<: *build_job
  tags: ["clang"]
  variables:
    CMAKE_OPTIONS: "-DCMAKE_BUILD_TYPE=Debug -DSOLL_INCLUDE_TESTS=true -DLLVM_EXTERNAL_LIT=${LIT_PATH}"
    KEY: "ubuntu-clang"

# Jobs for Ewasm Backend
compile:wasm:
  stage: compile
  image: secondstate/soll:ubuntu-compile
  needs: ["ubuntu-clang"]
  tags: ["clang"]
  variables:
    SOLL_PATH: "${BASE_BINDIR}/tools/soll/soll"
  script:
    - bash -c "./utils/compile -v sol ewasm ${TEST_ENVDIR}/test/*.sol"
    - bash -c "./utils/compile -v yul ewasm test/yul/switch.yul"
    - bash -c "./utils/compile -v yul ewasm test/yul/tuple.yul"
  after_script:
    - cp ${TEST_ENVDIR}/test/*.wasm ${BASE_BINDIR}
    - cp test/yul/*.wasm ${BASE_BINDIR}
  cache:
    <<: *cache_paths
    key: ubuntu-clang
    policy: pull-push

test:wasm:
  stage: test
  image: secondstate/soll:ubuntu-test
  needs: ["compile:wasm"]
  tags: ["clang"]
  before_script:
    - cp ${BASE_BINDIR}/*.wasm ${TEST_ENVDIR}/test
  script:
    - bash -c "cd ${BASE_BINDIR} && ctest"
    - bash -c "cd ${TEST_ENVDIR} && mocha"
    - bash -c "cd ${TEST_ENVDIR} && ./index.js test/switch.wasm '' '{}'"
    - bash -c "cd ${TEST_ENVDIR} && ./index.js test/tuple.wasm '' '{}'"
  cache:
    <<: *cache_paths
    key: ubuntu-clang
    policy: pull

# Jobs for EVM backend
ubuntu-clang:evm:
  <<: *build_job
  tags: ["evm"]
  variables:
    CMAKE_OPTIONS: "-DCMAKE_BUILD_TYPE=Debug -DSOLL_INCLUDE_TESTS=true -DLLVM_EXTERNAL_LIT=${LIT_PATH} -DSOLL_ENABLE_EVM=true -DLLVM_CMAKE_PATH=${EVM_BINDIR}"
    KEY: "ubuntu-evm-llvm"

compile:evm:
  stage: compile
  image: secondstate/soll:ubuntu-evm-llvm
  needs: ["ubuntu-clang:evm"]
  tags: ["evm"]
  variables:
    SOLL_PATH: "${BASE_BINDIR}/tools/soll/soll"
  script:
    - bash -c "./utils/compile -v sol evm ${TEST_ENVDIR}/test/*.sol"
  cache:
    <<: *cache_paths
    key: ubuntu-evm-llvm
    policy: pull-push

# Jobs for Coverage Report
coverage:ubuntu:
  <<: *build_job
  tags: ["coverage"]
  variables:
    CMAKE_OPTIONS: "-DCMAKE_BUILD_TYPE=Debug -DSOLL_INCLUDE_TESTS=true -DSOLL_COVERAGE=true -DLLVM_EXTERNAL_LIT=${LIT_PATH} -DSOLL_ENABLE_EVM=true -DLLVM_CMAKE_PATH=${EVM_BINDIR}"
    KEY: "ubuntu-coverage"

coverage:test:
  stage: test
  image: secondstate/soll:ubuntu-coverage
  needs: ["coverage:ubuntu"]
  tags: ["coverage"]
  before_script:
    - cd ${BASE_BINDIR}
  script:
    - make -j2 coverage
  cache:
    <<: *cache_paths
    key: ubuntu-coverage
    policy: pull-push

pages:
  stage: deploy
  image: secondstate/soll:ubuntu-coverage
  needs: ["coverage:test"]
  tags: ["coverage"]
  script:
    - mv -v ${BASE_BINDIR}/coverage public
  cache:
    <<: *cache_paths
    key: ubuntu-coverage
    policy: pull
  artifacts:
    paths: ["public"]
  only:
    - master
