.build_job_template: &build_job
  stage: build
  image: yi2nd/${OS}-soll-build:${VERSION}-${COMPILER}
  before_script:
    - rm -rf build
    - mkdir build
    - cd build
  script:
    - cmake ..
    - make -j2
  cache:
    key: ${OS}_${VERSION}-${COMPILER}
    paths:
      - build
    policy: push

.test_job_template: &test_job
  stage: test
  image: yi2nd/${OS}-soll-test:${VERSION}
  before_script:
    - cd build
    - cp ../test/lity/safemath.lity test.lity
  script:
    - bash -c "./tools/soll/soll test.lity > test.ll"
    - bash -c "../utils/compile -v test.ll || true"
    - bash -c "soll-ewasm-env.js test.wasm div 16 7"
  cache:
    key: ${OS}_${VERSION}-${COMPILER}
    paths:
      - build
    policy: pull

build:ubuntu-gcc:
  <<: *build_job
  variables:
    OS: "ubuntu"
    VERSION: "18.04"
    COMPILER: "gcc"

build:ubuntu-clang:
  <<: *build_job
  variables:
    OS: "ubuntu"
    VERSION: "18.04"
    COMPILER: "clang"

test:ubuntu-gcc:
  <<: *test_job
  variables:
    OS: "ubuntu"
    VERSION: "18.04"
    COMPILER: "gcc"

test:ubuntu-clang:
  <<: *test_job
  variables:
    OS: "ubuntu"
    VERSION: "18.04"
    COMPILER: "clang"
